// // Autogenerated with StateSmith 0.22.1-alpha-1+63e5c1c8f4246c6c2d862264aeda8f4ba0a27f54.
// // Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms
//
// #nullable enable
//
// using System;
// using Unity.Entities;
// using Unity.Mathematics;
// using BovineLabs.Core;
// using BovineLabs.Essence;
// using BovineLabs.Essence.Data;
// using BovineLabs.Core.Utility; // For GlobalRandom if needed, or we use Unity.Mathematics.Random
//
//
// // Generated state machine
// public partial class DaggerfallCombatSm
// {
//     // 1. --- BOVINELABS ESSENCE FACET ---
//     // Represents the Defender's ECS Components
//     public partial struct DefenderFacet : IFacet
//     {
//         public DynamicBuffer<Stat> Stats;
//         public IntrinsicWriter Intrinsics;
//     }
//
//     // 2. --- ESSENCE KEYS ---
//     public static class StatKeys
//     {
//         public const ushort ArmorClass = 1; // Lower is better in Daggerfall, but we'll adapt it
//         public const ushort Agility = 2;
//         public const ushort Luck = 3;
//         public const ushort Dodging = 4;
//
//         public const ushort MinMaterialToHit = 10; // e.g., 2 = Silver, 5 = Mithril
//
//         public const ushort ResistFire = 20;
//         public const ushort ResistFrost = 21;
//         public const ushort ResistPoison = 22;
//         public const ushort ResistShock = 23;
//         public const ushort ResistMagic = 24;
//     }
//
//     public static class IntrinsicKeys
//     {
//         public const ushort Health = 1;
//         public const ushort Fatigue = 2;
//     }
//
//     public enum DamageElement : byte
//     {
//         Physical = 0,
//         Fire = 1,
//         Frost = 2,
//         Poison = 3,
//         Shock = 4,
//         Magic = 5
//     }
//
//     // 3. --- STATE MACHINE FIELDS ---
//
//     // Attacker Inputs (passed in before DispatchEvent)
//     public int AttackerWeaponSkill;
//     public int AttackerAgility;
//     public int AttackerLuck;
//     public int AttackerMaterialLevel; // 0=Iron, 1=Steel, 2=Silver, ... 9=Daedric
//     public int AttackerMinDamage;
//     public int AttackerMaxDamage;
//     public DamageElement AttackElement;
//     public uint RandomSeed;
//
//     // Flow State (calculated during the graph execution)
//     public bool IsHit;
//     public bool IsMaterialEffective;
//     public bool IsResisted;
//     public int FinalDamage;
//
//     // ECS Context
//     public DefenderFacet Defender;
//
//     // Internal Random state
//     private Unity.Mathematics.Random _rng;
//
//     // 4. --- CALCULATION STEP METHODS ---
//
//     private void InitCombat()
//     {
//         _rng = new Unity.Mathematics.Random(RandomSeed == 0 ? 1 : RandomSeed);
//         IsHit = false;
//         IsMaterialEffective = false;
//         IsResisted = false;
//         FinalDamage = 0;
//         Console.WriteLine("--- Daggerfall Combat Sequence Started ---");
//     }
//
//     private void DoRollToHit()
//     {
//         // Attacker Hit Chance
//         int hitChance = AttackerWeaponSkill + (AttackerAgility / 10) + (AttackerLuck / 10);
//
//         // Defender Evasion
//         int defArmorClass = Defender.Stats.GetValueFloor(StatKeys.ArmorClass, 0);
//         int defAgility = Defender.Stats.GetValueFloor(StatKeys.Agility, 50);
//         int defLuck = Defender.Stats.GetValueFloor(StatKeys.Luck, 50);
//         int defDodging = Defender.Stats.GetValueFloor(StatKeys.Dodging, 0);
//
//         int evasion = defArmorClass + (defAgility / 10) + (defLuck / 10) + (defDodging / 4);
//
//         // Daggerfall hit formula approximation
//         int targetRoll = hitChance - evasion;
//         targetRoll = math.clamp(targetRoll, 3, 97); // 3% min chance, 97% max chance
//
//         int roll = _rng.NextInt(1, 101);
//         IsHit = roll <= targetRoll;
//
//         Console.WriteLine($"[To-Hit] Roll: {roll} vs Target: {targetRoll}. Hit? {IsHit}");
//     }
//
//     private void DoCheckMaterial()
//     {
//         int requiredMaterial = Defender.Stats.GetValueFloor(StatKeys.MinMaterialToHit, 0);
//         IsMaterialEffective = AttackerMaterialLevel >= requiredMaterial;
//
//         Console.WriteLine($"[Material] Weapon Material: {AttackerMaterialLevel}, Required: {requiredMaterial}. Effective? {IsMaterialEffective}");
//     }
//
//     private void DoCheckResistance()
//     {
//         if (AttackElement == DamageElement.Physical)
//         {
//             IsResisted = false;
//             return;
//         }
//
//         // Map element to stat key
//         ushort statKey = AttackElement switch
//         {
//             DamageElement.Fire => StatKeys.ResistFire,
//             DamageElement.Frost => StatKeys.ResistFrost,
//             DamageElement.Poison => StatKeys.ResistPoison,
//             DamageElement.Shock => StatKeys.ResistShock,
//             DamageElement.Magic => StatKeys.ResistMagic,
//             _ => 0
//         };
//
//         int resistance = Defender.Stats.GetValueFloor(statKey, 0); // 0-100%
//         int roll = _rng.NextInt(1, 101);
//         IsResisted = roll <= resistance;
//
//         Console.WriteLine($"[Resistance] Element: {AttackElement}, Resist Chance: {resistance}%, Roll: {roll}. Resisted? {IsResisted}");
//     }
//
//     private void DoCalcDamage()
//     {
//         // Weapon Damage Roll
//         FinalDamage = _rng.NextInt(AttackerMinDamage, AttackerMaxDamage + 1);
//
//         // Add Material Modifier (+1 damage per material level above steel generally, simplified here)
//         FinalDamage += math.max(0, AttackerMaterialLevel - 1);
//
//         Console.WriteLine($"[Damage] Calculated Damage: {FinalDamage}");
//     }
//
//     private void DoApplyDamage()
//     {
//         // BovineLabs Essence IntrinsicWriter automatically handles limits, death events, etc.
//         Defender.Intrinsics.Subtract(IntrinsicKeys.Health, FinalDamage);
//         Console.WriteLine($"[Apply] Deducted {FinalDamage} Health from Defender.");
//     }
//
//     private void LogMiss() => Console.WriteLine("[Result] Attack Missed.");
//     private void LogImmune() => Console.WriteLine("[Result] Defender is Immune to this material.");
//     private void LogResisted() => Console.WriteLine("[Result] Defender Resisted the attack.");
//
//     public enum EventId
//     {
//         DO = 0, // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
//         PROCESS_ATTACK = 1,
//     }
//
//     public const int EventIdCount = 2;
//
//     public enum StateId
//     {
//         ROOT = 0,
//         COMBAT_SEQUENCE = 1,
//         APPLY_DAMAGE = 2,
//         CALCULATE_DAMAGE = 3,
//         CHECK_HIT = 4,
//         CHECK_MATERIAL = 5,
//         CHECK_RESISTANCE = 6,
//         END_IMMUNE = 7,
//         END_MISS = 8,
//         END_RESISTED = 9,
//         IDLE = 10,
//     }
//
//     public const int StateIdCount = 11;
//
//     // Subtree meta data generation can be disabled in settings.
//     // Details: https://github.com/StateSmith/StateSmith/issues/538
//     public const int ROOT_SubtreeEndId = 10;  // State 'DaggerfallCombatSm' subtree extends from itself (id: 0) to state 'IDLE' (id: 10)
//     public const int COMBAT_SEQUENCE_SubtreeEndId = 9;  // State 'COMBAT_SEQUENCE' subtree extends from itself (id: 1) to state 'END_RESISTED' (id: 9)
//     public const int APPLY_DAMAGE_SubtreeEndId = 2;  // State 'APPLY_DAMAGE' subtree extends from itself (id: 2) to state 'APPLY_DAMAGE' (id: 2)
//     public const int CALCULATE_DAMAGE_SubtreeEndId = 3;  // State 'CALCULATE_DAMAGE' subtree extends from itself (id: 3) to state 'CALCULATE_DAMAGE' (id: 3)
//     public const int CHECK_HIT_SubtreeEndId = 4;  // State 'CHECK_HIT' subtree extends from itself (id: 4) to state 'CHECK_HIT' (id: 4)
//     public const int CHECK_MATERIAL_SubtreeEndId = 5;  // State 'CHECK_MATERIAL' subtree extends from itself (id: 5) to state 'CHECK_MATERIAL' (id: 5)
//     public const int CHECK_RESISTANCE_SubtreeEndId = 6;  // State 'CHECK_RESISTANCE' subtree extends from itself (id: 6) to state 'CHECK_RESISTANCE' (id: 6)
//     public const int END_IMMUNE_SubtreeEndId = 7;  // State 'END_IMMUNE' subtree extends from itself (id: 7) to state 'END_IMMUNE' (id: 7)
//     public const int END_MISS_SubtreeEndId = 8;  // State 'END_MISS' subtree extends from itself (id: 8) to state 'END_MISS' (id: 8)
//     public const int END_RESISTED_SubtreeEndId = 9;  // State 'END_RESISTED' subtree extends from itself (id: 9) to state 'END_RESISTED' (id: 9)
//     public const int IDLE_SubtreeEndId = 10;  // State 'IDLE' subtree extends from itself (id: 10) to state 'IDLE' (id: 10)
//
//     // Used internally by state machine. Feel free to inspect, but don't modify.
//     public StateId stateId;
//
//     // State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
//     public DaggerfallCombatSm()
//     {
//     }
//
//     // Starts the state machine. Must be called before dispatching events. Not thread safe.
//     public void Start()
//     {
//         ROOT_enter();
//         // ROOT behavior
//         // uml: TransitionTo(ROOT.<InitialState>)
//         {
//             // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
//             // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
//
//             // ROOT.<InitialState> behavior
//             // uml: TransitionTo(IDLE)
//             {
//                 // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
//
//                 // Step 2: Transition action: ``.
//
//                 // Step 3: Enter/move towards transition target `IDLE`.
//                 IDLE_enter();
//
//                 // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//                 return;
//             } // end of behavior for ROOT.<InitialState>
//         } // end of behavior for ROOT
//     }
//
//     // Dispatches an event to the state machine. Not thread safe.
//     // Note! This function assumes that the `eventId` parameter is valid.
//     public void DispatchEvent(EventId eventId)
//     {
//         switch (this.stateId)
//         {
//             // STATE: DaggerfallCombatSm
//             case StateId.ROOT:
//                 // No events handled by this state (or its ancestors).
//                 break;
//
//             // STATE: COMBAT_SEQUENCE
//             case StateId.COMBAT_SEQUENCE:
//                 // No events handled by this state (or its ancestors).
//                 break;
//
//             // STATE: APPLY_DAMAGE
//             case StateId.APPLY_DAMAGE:
//                 switch (eventId)
//                 {
//                     case EventId.DO: APPLY_DAMAGE_do(); break;
//                 }
//                 break;
//
//             // STATE: CALCULATE_DAMAGE
//             case StateId.CALCULATE_DAMAGE:
//                 switch (eventId)
//                 {
//                     case EventId.DO: CALCULATE_DAMAGE_do(); break;
//                 }
//                 break;
//
//             // STATE: CHECK_HIT
//             case StateId.CHECK_HIT:
//                 switch (eventId)
//                 {
//                     case EventId.DO: CHECK_HIT_do(); break;
//                 }
//                 break;
//
//             // STATE: CHECK_MATERIAL
//             case StateId.CHECK_MATERIAL:
//                 switch (eventId)
//                 {
//                     case EventId.DO: CHECK_MATERIAL_do(); break;
//                 }
//                 break;
//
//             // STATE: CHECK_RESISTANCE
//             case StateId.CHECK_RESISTANCE:
//                 switch (eventId)
//                 {
//                     case EventId.DO: CHECK_RESISTANCE_do(); break;
//                 }
//                 break;
//
//             // STATE: END_IMMUNE
//             case StateId.END_IMMUNE:
//                 switch (eventId)
//                 {
//                     case EventId.DO: END_IMMUNE_do(); break;
//                 }
//                 break;
//
//             // STATE: END_MISS
//             case StateId.END_MISS:
//                 switch (eventId)
//                 {
//                     case EventId.DO: END_MISS_do(); break;
//                 }
//                 break;
//
//             // STATE: END_RESISTED
//             case StateId.END_RESISTED:
//                 switch (eventId)
//                 {
//                     case EventId.DO: END_RESISTED_do(); break;
//                 }
//                 break;
//
//             // STATE: IDLE
//             case StateId.IDLE:
//                 switch (eventId)
//                 {
//                     case EventId.PROCESS_ATTACK: IDLE_process_attack(); break;
//                 }
//                 break;
//         }
//
//     }
//
//     // This function is used when StateSmith doesn't know what the active leaf state is at
//     // compile time due to sub states or when multiple states need to be exited.
//     private void ExitUpToStateHandler(StateId desiredState)
//     {
//         while (this.stateId != desiredState)
//         {
//             switch (this.stateId)
//             {
//                 case StateId.COMBAT_SEQUENCE: COMBAT_SEQUENCE_exit(); break;
//
//                 case StateId.APPLY_DAMAGE: APPLY_DAMAGE_exit(); break;
//
//                 case StateId.CALCULATE_DAMAGE: CALCULATE_DAMAGE_exit(); break;
//
//                 case StateId.CHECK_HIT: CHECK_HIT_exit(); break;
//
//                 case StateId.CHECK_MATERIAL: CHECK_MATERIAL_exit(); break;
//
//                 case StateId.CHECK_RESISTANCE: CHECK_RESISTANCE_exit(); break;
//
//                 case StateId.END_IMMUNE: END_IMMUNE_exit(); break;
//
//                 case StateId.END_MISS: END_MISS_exit(); break;
//
//                 case StateId.END_RESISTED: END_RESISTED_exit(); break;
//
//                 case StateId.IDLE: IDLE_exit(); break;
//
//                 default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
//             }
//         }
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state ROOT
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void ROOT_enter()
//     {
//         this.stateId = StateId.ROOT;
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state COMBAT_SEQUENCE
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void COMBAT_SEQUENCE_enter()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//
//         // COMBAT_SEQUENCE behavior
//         // uml: enter / { InitCombat(); }
//         {
//             // Step 1: execute action `InitCombat();`
//             InitCombat();
//         } // end of behavior for COMBAT_SEQUENCE
//     }
//
//     private void COMBAT_SEQUENCE_exit()
//     {
//         this.stateId = StateId.ROOT;
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state APPLY_DAMAGE
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void APPLY_DAMAGE_enter()
//     {
//         this.stateId = StateId.APPLY_DAMAGE;
//
//         // APPLY_DAMAGE behavior
//         // uml: enter / { DoApplyDamage(); }
//         {
//             // Step 1: execute action `DoApplyDamage();`
//             DoApplyDamage();
//         } // end of behavior for APPLY_DAMAGE
//     }
//
//     private void APPLY_DAMAGE_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void APPLY_DAMAGE_do()
//     {
//         // APPLY_DAMAGE behavior
//         // uml: do TransitionTo(IDLE)
//         {
//             // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
//             ExitUpToStateHandler(StateId.ROOT);
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `IDLE`.
//             IDLE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for APPLY_DAMAGE
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state CALCULATE_DAMAGE
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void CALCULATE_DAMAGE_enter()
//     {
//         this.stateId = StateId.CALCULATE_DAMAGE;
//
//         // CALCULATE_DAMAGE behavior
//         // uml: enter / { DoCalcDamage(); }
//         {
//             // Step 1: execute action `DoCalcDamage();`
//             DoCalcDamage();
//         } // end of behavior for CALCULATE_DAMAGE
//     }
//
//     private void CALCULATE_DAMAGE_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void CALCULATE_DAMAGE_do()
//     {
//         // CALCULATE_DAMAGE behavior
//         // uml: do TransitionTo(APPLY_DAMAGE)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CALCULATE_DAMAGE_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `APPLY_DAMAGE`.
//             APPLY_DAMAGE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CALCULATE_DAMAGE
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state CHECK_HIT
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void CHECK_HIT_enter()
//     {
//         this.stateId = StateId.CHECK_HIT;
//
//         // CHECK_HIT behavior
//         // uml: enter / { DoRollToHit(); }
//         {
//             // Step 1: execute action `DoRollToHit();`
//             DoRollToHit();
//         } // end of behavior for CHECK_HIT
//     }
//
//     private void CHECK_HIT_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void CHECK_HIT_do()
//     {
//         // CHECK_HIT behavior
//         // uml: do [IsHit] TransitionTo(CHECK_MATERIAL)
//         if (IsHit)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CHECK_HIT_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `CHECK_MATERIAL`.
//             CHECK_MATERIAL_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CHECK_HIT
//
//         // CHECK_HIT behavior
//         // uml: else do TransitionTo(END_MISS)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CHECK_HIT_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `END_MISS`.
//             END_MISS_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CHECK_HIT
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state CHECK_MATERIAL
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void CHECK_MATERIAL_enter()
//     {
//         this.stateId = StateId.CHECK_MATERIAL;
//
//         // CHECK_MATERIAL behavior
//         // uml: enter / { DoCheckMaterial(); }
//         {
//             // Step 1: execute action `DoCheckMaterial();`
//             DoCheckMaterial();
//         } // end of behavior for CHECK_MATERIAL
//     }
//
//     private void CHECK_MATERIAL_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void CHECK_MATERIAL_do()
//     {
//         // CHECK_MATERIAL behavior
//         // uml: do [IsMaterialEffective] TransitionTo(CHECK_RESISTANCE)
//         if (IsMaterialEffective)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CHECK_MATERIAL_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `CHECK_RESISTANCE`.
//             CHECK_RESISTANCE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CHECK_MATERIAL
//
//         // CHECK_MATERIAL behavior
//         // uml: else do TransitionTo(END_IMMUNE)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CHECK_MATERIAL_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `END_IMMUNE`.
//             END_IMMUNE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CHECK_MATERIAL
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state CHECK_RESISTANCE
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void CHECK_RESISTANCE_enter()
//     {
//         this.stateId = StateId.CHECK_RESISTANCE;
//
//         // CHECK_RESISTANCE behavior
//         // uml: enter / { DoCheckResistance(); }
//         {
//             // Step 1: execute action `DoCheckResistance();`
//             DoCheckResistance();
//         } // end of behavior for CHECK_RESISTANCE
//     }
//
//     private void CHECK_RESISTANCE_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void CHECK_RESISTANCE_do()
//     {
//         // CHECK_RESISTANCE behavior
//         // uml: do [!IsResisted] TransitionTo(CALCULATE_DAMAGE)
//         if (!IsResisted)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CHECK_RESISTANCE_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `CALCULATE_DAMAGE`.
//             CALCULATE_DAMAGE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CHECK_RESISTANCE
//
//         // CHECK_RESISTANCE behavior
//         // uml: else do TransitionTo(END_RESISTED)
//         {
//             // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition).
//             CHECK_RESISTANCE_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `END_RESISTED`.
//             END_RESISTED_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for CHECK_RESISTANCE
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state END_IMMUNE
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void END_IMMUNE_enter()
//     {
//         this.stateId = StateId.END_IMMUNE;
//
//         // END_IMMUNE behavior
//         // uml: enter / { LogImmune(); }
//         {
//             // Step 1: execute action `LogImmune();`
//             LogImmune();
//         } // end of behavior for END_IMMUNE
//     }
//
//     private void END_IMMUNE_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void END_IMMUNE_do()
//     {
//         // END_IMMUNE behavior
//         // uml: do TransitionTo(IDLE)
//         {
//             // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
//             ExitUpToStateHandler(StateId.ROOT);
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `IDLE`.
//             IDLE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for END_IMMUNE
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state END_MISS
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void END_MISS_enter()
//     {
//         this.stateId = StateId.END_MISS;
//
//         // END_MISS behavior
//         // uml: enter / { LogMiss(); }
//         {
//             // Step 1: execute action `LogMiss();`
//             LogMiss();
//         } // end of behavior for END_MISS
//     }
//
//     private void END_MISS_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void END_MISS_do()
//     {
//         // END_MISS behavior
//         // uml: do TransitionTo(IDLE)
//         {
//             // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
//             ExitUpToStateHandler(StateId.ROOT);
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `IDLE`.
//             IDLE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for END_MISS
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state END_RESISTED
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void END_RESISTED_enter()
//     {
//         this.stateId = StateId.END_RESISTED;
//
//         // END_RESISTED behavior
//         // uml: enter / { LogResisted(); }
//         {
//             // Step 1: execute action `LogResisted();`
//             LogResisted();
//         } // end of behavior for END_RESISTED
//     }
//
//     private void END_RESISTED_exit()
//     {
//         this.stateId = StateId.COMBAT_SEQUENCE;
//     }
//
//     private void END_RESISTED_do()
//     {
//         // END_RESISTED behavior
//         // uml: do TransitionTo(IDLE)
//         {
//             // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
//             ExitUpToStateHandler(StateId.ROOT);
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `IDLE`.
//             IDLE_enter();
//
//             // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//             return;
//         } // end of behavior for END_RESISTED
//
//         // No ancestor handles this event.
//     }
//
//
//     ////////////////////////////////////////////////////////////////////////////////
//     // event handlers for state IDLE
//     ////////////////////////////////////////////////////////////////////////////////
//
//     private void IDLE_enter()
//     {
//         this.stateId = StateId.IDLE;
//     }
//
//     private void IDLE_exit()
//     {
//         this.stateId = StateId.ROOT;
//     }
//
//     private void IDLE_process_attack()
//     {
//         // IDLE behavior
//         // uml: PROCESS_ATTACK TransitionTo(COMBAT_SEQUENCE)
//         {
//             // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
//             IDLE_exit();
//
//             // Step 2: Transition action: ``.
//
//             // Step 3: Enter/move towards transition target `COMBAT_SEQUENCE`.
//             COMBAT_SEQUENCE_enter();
//
//             // COMBAT_SEQUENCE.<InitialState> behavior
//             // uml: TransitionTo(CHECK_HIT)
//             {
//                 // Step 1: Exit states until we reach `COMBAT_SEQUENCE` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
//
//                 // Step 2: Transition action: ``.
//
//                 // Step 3: Enter/move towards transition target `CHECK_HIT`.
//                 CHECK_HIT_enter();
//
//                 // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
//                 return;
//             } // end of behavior for COMBAT_SEQUENCE.<InitialState>
//         } // end of behavior for IDLE
//
//         // No ancestor handles this event.
//     }
//
//     // Thread safe. This function can be disabled with `outputStateIdToStringFunction` setting.
//     public static string StateIdToString(StateId id)
//     {
//         switch (id)
//         {
//             case StateId.ROOT: return "ROOT";
//             case StateId.COMBAT_SEQUENCE: return "COMBAT_SEQUENCE";
//             case StateId.APPLY_DAMAGE: return "APPLY_DAMAGE";
//             case StateId.CALCULATE_DAMAGE: return "CALCULATE_DAMAGE";
//             case StateId.CHECK_HIT: return "CHECK_HIT";
//             case StateId.CHECK_MATERIAL: return "CHECK_MATERIAL";
//             case StateId.CHECK_RESISTANCE: return "CHECK_RESISTANCE";
//             case StateId.END_IMMUNE: return "END_IMMUNE";
//             case StateId.END_MISS: return "END_MISS";
//             case StateId.END_RESISTED: return "END_RESISTED";
//             case StateId.IDLE: return "IDLE";
//             default: return "?";
//         }
//     }
//
//     // Thread safe. This function can be disabled with `outputEventIdToStringFunction` setting.
//     public static string EventIdToString(EventId id)
//     {
//         switch (id)
//         {
//             case EventId.DO: return "DO";
//             case EventId.PROCESS_ATTACK: return "PROCESS_ATTACK";
//             default: return "?";
//         }
//     }
//
//     // Returns the parent state for a given state. Returns ROOT if input has no parent.
//     // Thread safe. This function can be disabled with `outputGetParentIdFunction` setting.
//     public static StateId GetParentId(StateId id)
//     {
//         switch (id)
//         {
//             case StateId.ROOT: return StateId.ROOT;
//             case StateId.COMBAT_SEQUENCE: return StateId.ROOT;
//             case StateId.APPLY_DAMAGE: return StateId.COMBAT_SEQUENCE;
//             case StateId.CALCULATE_DAMAGE: return StateId.COMBAT_SEQUENCE;
//             case StateId.CHECK_HIT: return StateId.COMBAT_SEQUENCE;
//             case StateId.CHECK_MATERIAL: return StateId.COMBAT_SEQUENCE;
//             case StateId.CHECK_RESISTANCE: return StateId.COMBAT_SEQUENCE;
//             case StateId.END_IMMUNE: return StateId.COMBAT_SEQUENCE;
//             case StateId.END_MISS: return StateId.COMBAT_SEQUENCE;
//             case StateId.END_RESISTED: return StateId.COMBAT_SEQUENCE;
//             case StateId.IDLE: return StateId.ROOT;
//             default: return StateId.ROOT;
//         }
//     }
// }
